env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - react-hooks
  - prettier
  - import
rules:
  {
    'react/react-in-jsx-scope': 'off',
    'camelcase': 'error',
    'spaced-comment': 'error',
    'quotes': ['error', 'single'],
    'no-duplicate-imports': 'error',
    'no-unreachable': 'error',
    'keyword-spacing': ['before', true],
    'jsx-quotes': [2, 'prefer-double'],
    'no-trailing-spaces':
      ['error', { 'ignoreComments': true, 'prefer-template': true }],
    'sort-imports':
      [
        'error',
        {
          'ignoreCase': false,
          'ignoreDeclarationSort': false,
          'ignoreMemberSort': false,
          'memberSyntaxSortOrder': ['all', 'multiple', 'single', 'none'],
          'allowSeparatedGroups': false,
        },
      ],
      "import/no-unresolved": "error"
  }
settings: { 'import/resolver': { 'typescript': { true } } }
